---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile
  provision: true


provisioner:
  name: dummy
  require_chef_omnibus: false
  require_ruby_for_busser: true
  require_chef_for_busser: false 

platforms:
  - name: mansm/CentOS-7

verifier:
  ruby_bindir: '/usr/bin'

suites:
  - name: default 
    run_list:
    attributes:
